// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "5.0.0-rc.0-119-g384fd4f4b-dirty"
#define MICROPY_GIT_HASH "384fd4f4b-dirty"
#define MICROPY_BUILD_DATE "2020-04-05"
#define MICROPY_VERSION_MAJOR (5)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (0)
#define MICROPY_VERSION_STRING "5.0.0"
#define MICROPY_FULL_VERSION_INFO ("Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_HW_BOARD_NAME " with " MICROPY_HW_MCU_NAME)
