// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "5.0.0-rc.0-13-gb5d88de51-dirty"
#define MICROPY_GIT_HASH "b5d88de51-dirty"
#define MICROPY_BUILD_DATE "2020-03-03"
#define MICROPY_VERSION_MAJOR (5)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (0)
#define MICROPY_VERSION_STRING "5.0.0"
#define MICROPY_FULL_VERSION_INFO ("Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_HW_BOARD_NAME " with " MICROPY_HW_MCU_NAME)
